services:
  gateway.api:
    image: ${DOCKER_REGISTRY-}gatewayapi:latest
    build:
      context: .
      dockerfile: Gateway.api/Dockerfile
    environment:
      - ASPNETCORE_URLS=https://+;http://+
      - ASPNETCORE_HTTPS_PORTS=7274
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Aditya#123
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - $USERPROFILE\.aspnet\https:/https/
    ports:
      - "7274:443"  
   
  microservice1:
    image: ${DOCKER_REGISTRY-}microservice1:latest
    build:
      context: .
      dockerfile: microservice1/Dockerfile
    environment:
      - ASPNETCORE_URLS=https://+;http://+
      - ASPNETCORE_HTTPS_PORTS=7014
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Aditya#123
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - $USERPROFILE\.aspnet\https:/https/
    ports:
      - "7014:443"
    depends_on:
        - gateway.api
