include:
  - docker-compose-dev-logging.yml

name: microservices-containers-identity

services:
  postgres:
    image: postgres
    container_name: microservices-identity-database
    volumes:
      - C:\Users\SESA670640\Desktop\postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  keycloak:
    image: quay.io/keycloak/keycloak
    container_name: microservices-keycloak-identity
    volumes:
      - ./Identity-Realm-Import:/opt/keycloak/data/import
      - ./Https-Certificates/localhost.crt:/opt/keycloak/conf/server.crt
      - ./Https-Certificates/localhost.key:/opt/keycloak/conf/server.key
    command: start-dev --import-realm
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: ${DB_PASSWORD}
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_HTTPS_CERTIFICATE_FILE: /opt/keycloak/conf/server.crt
      KC_HTTPS_CERTIFICATE_KEY_FILE: /opt/keycloak/conf/server.key
      KC_HTTP_RELATIVE_PATH: "/auth"
      KC_FEATURES: "preview,token-exchange"
      KC_HEALTH_ENABLED: true
    ports:
      - ${KEYCLOAK_HTTPS_SERVER_PORT}:${KEYCLOAK_HTTPS_SERVER_PORT}
    depends_on:
      - postgres

networks:
  "my-network":
    driver: bridge 