apiVersion: v1
kind: Service
metadata:
  labels:
    gateway-api-pod: gateway-api
  name: gateway-api
spec:
  type: ClusterIP
  ports:
    - name: "8081"
      port: 8081
      targetPort: 8081
  selector:
    gateway-api-pod: gateway-api
