apiVersion: v1
kind: Service
metadata:
  labels:
    microservice1-Pod: microservice1
  name: microservice1
spec:
  type: LoadBalancer
  ports:
    - name: "8081"
      port: 8081
      targetPort: 8081
  selector:
    microservice1-Pod: microservice1
