apiVersion: v1
kind: Service
metadata:
  name: mssql-headless
  labels:
    app: mssql
spec:
  ports:
    - name: tcpsql
      port: 1433
      targetPort: 1433
  clusterIP: None
  selector:
    app: mssql
