apiVersion: v1
kind: Service
metadata:
  labels:
    app-account-pod: app-account
  name: app-account
spec:
  type: LoadBalancer
  ports:
    - name: "4204"
      port: 4204
      targetPort: 443
  selector:
    app-account-pod: app-account
