apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: microservices-keycloak-identity
  name: microservices-keycloak-identity
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservices-keycloak-identity
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: microservices-keycloak-identity
    spec:
      volumes:
        - name: keycloak-pv-storage
          persistentVolumeClaim:
            claimName: azurefile
      containers:
        - args:
            - start-dev
            - --import-realm
          env:
            - name: DB_ADDR
              value: postgres
            - name: DB_DATABASE
              value: keycloak
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: DB_PASSWORD
                  name: microservices-secrets
            - name: DB_SCHEMA
              value: public
            - name: DB_USER
              value: keycloak
            - name: DB_VENDOR
              value: POSTGRES
            - name: KC_FEATURES
              value: preview,token-exchange
            - name: KC_HEALTH_ENABLED
              value: "true"
            - name: KC_HTTPS_CERTIFICATE_FILE
              value: /opt/keycloak/conf/server.crt
            - name: KC_HTTPS_CERTIFICATE_KEY_FILE
              value: /opt/keycloak/conf/server.key
            - name: KC_HTTP_RELATIVE_PATH
              value: /auth
            - name: KEYCLOAK_ADMIN
              value: admin
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: KEYCLOAK_ADMIN_PASSWORD
                  name: microservices-secrets
          image: quay.io/keycloak/keycloak:26.2.4
          name: microservices-keycloak-identity
          ports:
            - containerPort: 8443
          readinessProbe:
            httpGet:
              path: /auth/health/ready
              port: 9000
              scheme: HTTPS
            initialDelaySeconds: 60
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          volumeMounts:
            - mountPath: /opt/keycloak/data/import
              name: keycloak-pv-storage
              subPath: kubernetes-mount/Identity-Realm-Import
            - mountPath: /opt/keycloak/conf/server.crt
              name: keycloak-pv-storage
              subPath: kubernetes-mount/Https-Certificates/localhost.crt
            - mountPath: /opt/keycloak/conf/server.key
              name: keycloak-pv-storage
              subPath: kubernetes-mount/Https-Certificates/localhost.key
      restartPolicy: Always
---
apiVersion: v1
kind: Namespace
metadata:
  name: default
  labels:
    shared-gateway-access: "true"
