apiVersion: v1
kind: Service
metadata:
  name: microservices-keycloak-identity-svc
spec:
  type: ClusterIP
  ports:
    - port: 8443
      name: https-8443
      targetPort: 8443
  selector:
    app: microservices-keycloak-identity
