apiVersion: v1
kind: Service
metadata:
  labels:
    microservices-sqlserver-pod: microservices-sqlserver
  name: microservices-sqlserver
spec:
  type: LoadBalancer
  ports:
    - name: "1433"
      port: 1433
      protocol: TCP
      targetPort: 1433
  selector:
    microservices-sqlserver-pod: microservices-sqlserver
