apiVersion: v1
kind: Service
metadata:
  labels:
    microservice2-Pod: microservice2
  name: microservice2
spec:
  type: ClusterIP
  ports:
    - name: "8081"
      port: 8081
      targetPort: 8081
  selector:
    microservice2-Pod: microservice2
