apiVersion: v1
kind: Secret
metadata:
  name: azure-secret
type: Opaque
stringData:
  azurestorageaccountname: msstorage1991
  azurestorageaccountkey: 7eBEwDMVl9kAMpfvQeHRZetlR4JnqBV84tI8cSyrSCCqAOf3ZEuG06uvFUZt9H8FHfnCI7aC5nOh+AStaJKy+A==
