apiVersion: v1
kind: Service
metadata:
  labels:
    microservices-keycloak-identity-pod: microservices-keycloak-identity
  name: microservices-keycloak-identity
spec:
  type: LoadBalancer
  ports:
    - name: "8443"
      port: 8443
      targetPort: 8443
  selector:
    microservices-keycloak-identity-pod: microservices-keycloak-identity
