apiVersion: v1
kind: Service
metadata:
  labels:
    microservices-keycloak-identity-pod: microservices-keycloak-identity
  name: microservices-keycloak-identity
spec:
  type: NodePort
  ports:
    - port: 8443
      targetPort: 8443
      nodePort: 30000
  selector:
    microservices-keycloak-identity-pod: microservices-keycloak-identity
