apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: mf-http-route-shell
  namespace: gloo-system
  labels:
    gateway: ms-gateway
spec:
  parentRefs:
    - name: ms-gateway
      namespace: gloo-system
      sectionName: ms-gateway
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
        - path:
            type: PathPrefix
            value: /mf-shell
      backendRefs:
        - name: mf-shell-upstream
          kind: Upstream
          group: gloo.solo.io
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: mf-http-route-account
  namespace: gloo-system
  labels:
    gateway: ms-gateway
spec:
  parentRefs:
    - name: ms-gateway
      namespace: gloo-system
      sectionName: ms-gateway
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /mf-account
      backendRefs:
        - name: mf-account-upstream
          kind: Upstream
          group: gloo.solo.io

---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: mf-http-route-customer
  namespace: gloo-system
  labels:
    gateway: ms-gateway
spec:
  parentRefs:
    - name: ms-gateway
      namespace: gloo-system
      sectionName: ms-gateway
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /mf-customer
      backendRefs:
        - name: mf-customer-upstream
          kind: Upstream
          group: gloo.solo.io

---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: mf-http-route-login
  namespace: gloo-system
  labels:
    gateway: ms-gateway
spec:
  parentRefs:
    - name: ms-gateway
      namespace: gloo-system
      sectionName: ms-gateway
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /mf-login
      backendRefs:
        - name: mf-login-upstream
          kind: Upstream
          group: gloo.solo.io

---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: mf-http-route-transaction
  namespace: gloo-system
  labels:
    gateway: ms-gateway
spec:
  parentRefs:
    - name: ms-gateway
      namespace: gloo-system
      sectionName: ms-gateway
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /mf-transaction
      backendRefs:
        - name: mf-transaction-upstream
          kind: Upstream
          group: gloo.solo.io
